CREATE DATABASE PROJECT_WORK;
USE PROJECT_WORK;

SELECT *FROM FOREST;
SELECT *FROM LAND;
SELECT *FROM REGION;
SELECT COUNT(DISTINCT COUNTRY_NAME)AS COUNTRIES_NOT_INVOLVED_IN_DEFORESTATION FROM FOREST WHERE FOREST_AREA_SQKM !=0;

SELECT *FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE TOTAL_AREA_SQ_MI BETWEEN 75000 AND 150000
ORDER BY TOTAL_AREA_SQ_MI;

SELECT AVG (TOTAL_AREA_SQ_MI)FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'UPPER MIDDLE INCOME';


SELECT COUNT(F.COUNTRY_CODE) FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'HIGH INCOME';


SELECT *FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE F.COUNTRY_NAME='AUSTRALIA'ORDER BY FOREST_AREA_SQKM DESC;

WITH EDDY_CTE AS
(SELECT  DISTINCT FOREST.COUNTRY_NAME, REGION.REGION,FOREST_AREA_SQKM,
ROW_NUMBER() OVER(PARTITION BY REGION.REGION ORDER BY FOREST_AREA_SQKM DESC) AS RANK FROM REGION
JOIN FOREST ON REGION.COUNTRY_CODE=FOREST.COUNTRY_CODE)
SELECT *FROM EDDY_CTE
WHERE RANK = 1





