CREATE DATABASE PROJECT_WORK;
USE PROJECT_WORK;

SELECT *FROM FOREST;
SELECT *FROM LAND;
SELECT *FROM REGION;
SELECT COUNT (DISTINCT COUNTRY_NAME ) FROM REGION----THERE IS DUPLICATE
SELECT COUNT(DISTINCT COUNTRY_NAME) FROM FOREST----THERE IS DUPLICATE
SELECT COUNT(DISTINCT COUNTRY_NAME) FROM LAND-----THERE IS DUPLICATE

---WHAT ARE THE TOTAL NUMBER OF COUNTRIES INVOLVED IN DEFORESTATION?---

/*ANSWER TO QUESTION 1*/
SELECT COUNT(DISTINCT COUNTRY_NAME)AS COUNTRIES_NOT_INVOLVED_IN_DEFORESTATION FROM FOREST WHERE FOREST_AREA_SQKM !=0;

---INSIGHT
--SELECT COUNT DISTINCT COUNTRY_NAME AS COUNTRIES_NOT_INVOLVED_IN_DEFORESTATION FROM FOREST WHERE FOREST_AREA_SQKM=0---

---Q2 SHOW THE INCOME GROUPS OF COUNTRIES HAVING TOTAL AREA RANGING FROM 75,000 TO 150,000 SQUARE METER?

/*ANSWER TO QUESTION 2*/

SELECT DISTINCT REGION.COUNTRY_NAME,INCOME_GROUP FROM REGION FULL JOIN LAND ON REGION.COUNTRY_CODE=LAND.COUNTRY_CODE
WHERE TOTAL_AREA_SQ_MI BETWEEN 75000 AND 150000;


---INSIGHT---
--FROM THE ANALYSIS ABOVE,ONLY 26 COUNTRIES HAVE TOTAL AREA RANGING FROM 75,000 TO 150,000 SQUARE METER----

--Q3 CALCULATE AVERAGE AREA IN SQUARE MILES FOR COUNTRIES IN THE 'UPPER MIDDLE INCOME REGION'COMPARE THE RESULT WITH THE REST OF THE INCOME CATEGORY--

/*ANSWER TO QUESTION 3*/
SELECT AVG (TOTAL_AREA_SQ_MI)FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'UPPER MIDDLE INCOME';

SELECT AVG (TOTAL_AREA_SQ_MI)FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'HIGH INCOME';
SELECT AVG (TOTAL_AREA_SQ_MI)FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'LOW INCOME';

SELECT AVG (TOTAL_AREA_SQ_MI)FROM LAND F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'LOWER MIDDLE INCOME';

--INSIGHT--
--THE UPPER MIDDLE INCOME=390072.34,AVERAGE OF HIGH INCOME= 186746.88,AVERAGE OF LOW INCOME=170275.70 AND THE AVERAGE OF LOWER MIDDLE INCOME=174123
--WTH THE ANALYSIS ABOVE,THE UPPER MIDDLE INCOME HAS THE HIGHEST AVERAGE AREA IN SQUARE MILES--

---Q4  DETERMINE THE TOTAL FOREST AREA IN SQUARE KM FOR COUNTRIES IN THE 'HIGH INCOME'GROUP.COMPARE RESULT WITH THE REST OF THE  INCOME  CATEGORIES--

/*ANSWER TO QUESTION 4*/
SELECT COUNT(F.COUNTRY_CODE) FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'HIGH INCOME';
SELECT COUNT(F.COUNTRY_CODE) FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'LOW INCOME';
SELECT COUNT(F.COUNTRY_CODE) FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'LOWER MIDDLE INCOME';
SELECT COUNT(F.COUNTRY_CODE) FROM FOREST F
JOIN REGION R ON F.COUNTRY_CODE=R.COUNTRY_CODE AND F.COUNTRY_NAME=R.COUNTRY_NAME
WHERE INCOME_GROUP = 'UPPER MIDDLE INCOME';

--THE UPPER MIDDLE INCOME=1485,HIGH INCOME= 2133,LOW INCOME=891 AND LOWER MIDDLE INCOME=1188
--WITH THE ANALYSIS ABOVE,THE HIGH INCOME HAS THE HIGHEST TOTAL FOREST AREA IN SQUARE KM--


---SHOW COUNTRIES FROM EACH REGION(CONTINENT)HAVING THE HIGHEST TOTAL FOREST AREAS---


SELECT REGION,REGION.country_name,SUM(FOREST_AREA_SQKM)AS TOTAL_FOREST_AREA FROM FOREST FULL JOIN REGION ON FOREST.COUNTRY_CODE=REGION.COUNTRY_CODE
GROUP BY  REGION,REGION.COUNTRY_NAME
ORDER BY SUM(FOREST_AREA_SQKM)DESC;



WITH EDDY_CTE AS
(SELECT  DISTINCT FOREST.COUNTRY_NAME, REGION.REGION,FOREST_AREA_SQKM,
ROW_NUMBER() OVER(PARTITION BY REGION.REGION ORDER BY FOREST_AREA_SQKM DESC) AS RANK FROM REGION
JOIN FOREST ON REGION.COUNTRY_CODE=FOREST.COUNTRY_CODE)
SELECT *FROM EDDY_CTE
WHERE RANK = 1

---INSIGHT---
--FROM THE RANKING ABOVE BRAZIL FROM LATIN AMERICA AND CARIBBEAN HAS THE HIGHEST FOREST AREA SQKM WITH A FIGURE OF 5467050SQMI,FOLLOWED BY CANADA 
--FROM NORTH AMERICA WITH A FIGURE OF 3482730SQMI,CHINA FROM EAST ASAIA AND PACIFIC WITH A FIGURE 2098635SQMI,CONGO.DEM.REP FROM SUB-SAHARAN AFRICA
--WITH A FIGURE 1603630SQMI,INDIA FROM SOUTH ASIA WITH A FIGURE 708604SQMI,IRAN.ISLAMIC REP FROM MIDDLE EAST AND NORTH AFRICA WITH FIGURE 106919.805SQMI
--RUSSIAN FEDERATION FROM EUROPE AND CENTRAL ASIA WITH A FIGURE 8151356SQMI AND WORLD FROM WORLD WITH FIGURE 41282696SQMI---





